import { FuseNavigation } from '@fuse/types';

export const navigation: FuseNavigation[] = [
	{
		id				: 'menu',
		title			: 'Main menu',
		type			: 'group',
		children	: [
			{
				id			: 'home',
				title		: 'Home',
				type		: 'item',
				icon		: 'home',
				url			: '/pages/home',
			},
			{
				id			: 'create-new-vehicle',
				title		: 'Create new vehicle',
				type		: 'item',
				icon		: 'add_box',
				url			: '/pages/create-new-vehicle',
			},
			{
				id			: 'create-new-ad',
				title		: 'Create new ad',
				type		: 'item',
				icon		: 'add_circle_outline',
				url			: '/pages/create-new-ad',
			},
			{
				id			: 'search-ad',
				title		: 'Search ad',
				type		: 'item',
				icon		: 'search',
				url			: '/pages/search-ad',
			},
			{
				id			: 'advanced-search-ad',
				title		: 'Advanced search vehicles',
				type		: 'item',
				icon		: 'pageview',
				url			: '/pages/advanced-search',
			},
			{
				id			: 'request-to-rent',
				title		: 'Requests to rent',
				type		: 'item',
				icon		: 'account_balance',
				url			: '/pages/request-to-rent',
			},
			{
				id			: 'request-to-rent-details',
				title		: 'Requests to rent details',
				type		: 'item',
				icon		: 'description',
				url			: '/pages/request-to-rent-details',
			},
			{
				id			: 'qualified-users',
				title		: 'Qualified users',
				type		: 'item',
				icon		: 'description',
				url			: '/pages/qualified-users',
			},
			{
				id			: 'agent-list',
				title		: 'Agents',
				type		: 'item',
				icon		: 'description',
				url			: '/pages/agent-list',
			},
			{
				id			: 'transporationVehicle-list',
				title		: 'transporationVehicles',
				type		: 'item',
				icon		: 'description',
				url			: '/pages/transportationVehicle-list',
			},
			{
				id			: 'other-agencies-list',
				title		: 'other Agencies',
				type		: 'item',
				icon		: 'description',
				url			: '/pages/other-agencies',
			},
			{
				id			: 'transporationVehicle-list',
				title		: 'create transpotration vehicle',
				type		: 'item',
				icon		: 'description',
				url			: '/pages/create-transportationVehicle',
			},
			{
				id			: 'messages',
				title		: 'Messages',
				type		: 'item',
				icon		: 'message',
				url			: '/pages/messages',
			},
			{
				id			: 'chat',
				title		: 'Chat',
				type		: 'item',
				icon		: 'chat',
				url			: '/pages/chat',
			},
			{
				id			: 'user-access',
				title		: 'User access',
				type		: 'item',
				icon		: 'user_group',
				url			: '/pages/user-access',
			},
			{
				id			: 'image',
				title		: 'Add Images',
				type		: 'item',
				icon		: 'image',
				url			: '/pages/add-images',
			},
			{
				id			: 'codebook',
				title		: 'Codebook',
				type		: 'collapsable',
				icon		: 'import_contacts',
				children	: [
					{
						id			: 'fuel-types',
						title		: 'Fuel Types',
						type		: 'item',
						url			: '/pages/fuel-types',
					},
					{
						id			: 'transmission-types',
						title		: 'Transmission Types',
						type		: 'item',
						url			: '/pages/transmission-types',
					},
					{
						id			: 'vehicle-types',
						title		: 'Vehicle Types',
						type		: 'item',
						url			: '/pages/vehicle-types',
					},
				],
			},
			{
				id			: 'cart',
				title		: 'Cart',
				type		: 'item',
				icon		: 'shopping_cart',
				url			: '/pages/cart',
			},
			{
				id			: 'register',
				title		: 'Register',
				type		: 'item',
				icon		: 'person',
				url			: '/pages/register',
			},
		],
	},
];
